### ISSUE TITLE
Quiz Retaking

### ISSUE THREAD

**Issue by xtian18** [Iionsroar/inquizitor#18]
tried retaking a quiz, new answers are just appended and returns 6 answers even though there are only 3 questions.
![Capture](https://user-images.githubusercontent.com/58137485/167797413-5d3be2c2-8b6b-402a-9f87-4a5220be1f14.PNG)

**Comment by Iionsroar** [comment]
**backend** working on:

##### GET /quizzes/{quiz_index}/finish 
- make sure attempt for this session exists
- update attempt object `is_done`

##### PUT /quizzes/{quiz_index}/questions/{question_id}/answer
- validate attempt object
    - if `is_done` create a new one

##### CRUDQuizAttempt: get_score
- get using `attempt` only instead of `quiz and student` 

##### Quiz models
- _QuizAnswer:_ add `attempt_id`
- _QuizAttempt:_ add `datetime_started` (for showing only the latest attempt)

**Comment by Iionsroar** [comment]
@xtian18 nag add ako ng scores sa `GET /quizzes/' ng students

**Comment by Iionsroar** [comment]
fixes were merged to main through the branch `rapid-dev`
